import { createAsyncThunk, createSlice, AsyncThunk } from "@reduxjs/toolkit"
import { TimeState } from "./timesState";
import { WebWorkerManager } from "@shared/core/services/workers/webWorkerManager.service";
import { CitiesEnum } from "@shared/core/services/workers/handlers/models/shared-models";
import { TypedObjectMap } from "@shared/models/shared";
import { StateKeys } from "../../../store.models";
const workersManager = WebWorkerManager.getInstance();

export const calculateTimes = createAsyncThunk(
    "times/calculateTimes",
    (metadata: { date: Date, location: CitiesEnum }, thankAPI) => {
        workersManager.calculateTimes<TypedObjectMap<Date>>({ date: metadata.date, location: metadata.location }).subscribe((res: TypedObjectMap<Date>) => {
            thankAPI.dispatch(setTimes(res))
        });
    },
)

const initialState: TimeState = {};
export const timesSlice = createSlice({
    name: StateKeys.Times,
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setTimes: (state, action) => {
            return { ...state, ...action.payload };
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    //extraReducers: (builder) => {
    //    builder
    //        .addCase(calculateTimes.pending, (state) => {
    //            state.status = "loading"
    //        })
    //        .addCase(calculateTimes.fulfilled, (state, action) => {
    //            state.status = "idle"
    //            state.value += action.payload
    //        })
    //        .addCase(calculateTimes.rejected, (state) => {
    //            state.status = "failed"
    //        })
    //},
})

export const { setTimes } = timesSlice.actions;

export default timesSlice.reducer;