import { createAsyncThunk, createSlice, AsyncThunk } from "@reduxjs/toolkit"
import { TimeState } from "./timeState";
import { WebWorkerManager } from "@shared/core/services/workers/webWorkerManager.service";

const workersManager = WebWorkerManager.getInstance();

export const calculateTimes = createAsyncThunk(
    "times/calculateTimes",
    (worker: string, thankAPI) => {
        workersManager.startTask().subscribe(res=>{
            thankAPI.dispatch(setTimes(['time1', 'time2']))
        })
    },
)
const initialState: TimeState ={
    times: []
}

export const timeSlice = createSlice({
    name: "times",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setTimes: (state, action) => {
            state.times = action.payload;
            return state;
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    //extraReducers: (builder) => {
    //    builder
    //        .addCase(calculateTimes.pending, (state) => {
    //            state.status = "loading"
    //        })
    //        .addCase(calculateTimes.fulfilled, (state, action) => {
    //            state.status = "idle"
    //            state.value += action.payload
    //        })
    //        .addCase(calculateTimes.rejected, (state) => {
    //            state.status = "failed"
    //        })
    //},
})

export const { setTimes } = timeSlice.actions;

export default timeSlice.reducer;