import { createAsyncThunk, createSlice, AsyncThunk } from "@reduxjs/toolkit"
import { TitlesState } from "./titlesState";
import { WebWorkerManager } from "@shared/core/services/workers/webWorkerManager.service";
import { CitiesEnum, IClockTitle } from "@shared/core/services/workers/handlers/models/shared-models";
import { TypedMap } from "@shared/models/shared";
import { StateKeys } from "../../../store.models";

import { enableMapSet } from 'immer';

enableMapSet()
const workersManager = WebWorkerManager.getInstance();


export const calculateTitles = createAsyncThunk(
    "times/calculateTitles",
    (metadata: {date: Date, location: CitiesEnum}, thankAPI) => {
        workersManager.calculateTitles<TypedMap<IClockTitle>>({date: metadata.date, location: metadata.location}).subscribe((res: TypedMap<IClockTitle>)=>{
            thankAPI.dispatch(setTitles(res))
        });
    },
)
const initialState: TitlesState = {};

export const titlesSlice = createSlice({
    name: StateKeys.Titles,
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setTitles: (state, action)=>{
            return {};
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    //extraReducers: (builder) => {
    //    builder
    //        .addCase(calculateTimes.pending, (state) => {
    //            state.status = "loading"
    //        })
    //        .addCase(calculateTimes.fulfilled, (state, action) => {
    //            state.status = "idle"
    //            state.value += action.payload
    //        })
    //        .addCase(calculateTimes.rejected, (state) => {
    //            state.status = "failed"
    //        })
    //},
})

export const { setTitles } = titlesSlice.actions;

export default titlesSlice.reducer;